# Generated by Django 4.2 on 2024-12-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoapp', '0003_remove_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
