# Generated by Django 4.2 on 2024-12-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoapp', '0008_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
